---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: mediawiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deploy
spec:
  selector:
    matchLabels:
      run: mediawiki
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
      labels:
        run: mediawiki
    spec:
      containers:
      - name: mediawiki
#        image: wikimedia/mediawiki:1.30.0-wmf4
        image: localhost:5000/mediawiki-1.30.0-wmf4
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /wiki/Main_Page
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /wiki/Main_Page
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        env:
          - name: MEDIAWIKI_SITE_SERVER
            value: 'configured-in-CustomSettings.php'
          - name: MEDIAWIKI_SITE_NAME
            value: opsschool
          - name: MEDIAWIKI_SITE_LANG
            value: en
          - name: MEDIAWIKI_ADMIN_USER
            value: admin
          - name: MEDIAWIKI_ADMIN_PASS
            value: admin
          - name: MEDIAWIKI_DB_USER
            value: media
          - name: MEDIAWIKI_DB_PASSWORD
            value: media
          - name: MEDIAWIKI_DB_HOST
            value: mysql-outside
        volumeMounts:
          - name: mediawiki-storage
            mountPath: /data
          - name: mediawiki-logs
            mountPath: /var/log/mediawiki
          - name: mediawiki-conf
            mountPath: /conf
      volumes:
        - name: mediawiki-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mediawiki
        - name: mediawiki-logs
          hostPath:
            path: /var/log/mediawiki
        - name: mediawiki-conf
          configMap:
            name: mediawiki-conf-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki-conf-1
data:
  CustomSettings.php: |
    <?php

    $wgServer = '//' . $_SERVER['HTTP_HOST'];
    $wgArticlePath = '/wiki/$1';
    $wgScriptPath = '/w';
    $wgLogo = 'http://static.wixstatic.com/media/ba2a09_ecc8fa38369346adad30553fa107f27e~mv2.png';
    $wgDebugLogFile = "/var/log/mediawiki/debug-{$wgDBname}.log";
