kind: Service
apiVersion: v1
metadata:
 name: mysql-outside
spec:
 ports:
 - port: 3306
   targetPort: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
 name: mysql-outside
subsets:
 - addresses:
     - ip: {{ mysql_outside_addr.output }}
   ports:
     - port: 3306
