output:
  logstash:
    hosts: ["{{ kibana_ip }}:5044"]

filebeat:
  prospectors:
    -
      paths:
        - /var/log/syslog
        - /var/log/auth.log
      document_type: system
    -
      paths:
        - /var/log/haproxy
      document_type: haproxy
    -  
      paths:
        - /var/log/mysql/*
      document_type: mysql
    -  
      paths:
        - /var/log/mediawiki/
      document_type: mediawiki
    -   
      paths:
        - /var/lib/docker/containers/*/*.log
      document_type: docker
