---

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Copy /etc/hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Disable host checking in ssh
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"
