---
- name: Create key and CSR
  command: icinga2 pki new-cert --cn {{ ansible_hostname }} --key /tmp/{{ ansible_hostname }}.key --csr /tmp/{{ ansible_hostname }}.csr
  delegate_to: "{{ icinga_ip }}"

- name: Generate certificate
  command: icinga2 pki sign-csr --csr /tmp/{{ ansible_hostname }}.csr --cert /tmp/{{ ansible_hostname }}.crt
  delegate_to: "{{ icinga_ip }}"

- name: Fetch SSL credentials to ansible mgmt host
  fetch: src=/tmp/{{ item }} dest=/tmp/ flat=yes
  with_items:
  - "{{ ansible_hostname }}.crt"
  - "{{ ansible_hostname }}.key"
  delegate_to: "{{ icinga_ip }}"

- name: Delete SSL credentials from {{ icinga_ip }}
  file: path=/tmp/{{ item }} state=absent
  with_items:
  - "{{ ansible_hostname }}.crt"
  - "{{ ansible_hostname }}.key"
  - "{{ ansible_hostname }}.csr"
  delegate_to: "{{ icinga_ip }}"

- name: Copy SSL credentials to machine
  copy: src=/tmp/{{ item }} dest=/etc/icinga2/pki/{{ item }}
  with_items:
  - "{{ ansible_hostname }}.key"
  - "{{ ansible_hostname }}.crt"
  notify: Restart icinga client

- name: Delete SSL credentials from ansible mgmt host
  local_action: file path=/tmp/{{ item }} state=absent
  become: no
  with_items:
  - "{{ ansible_hostname }}.crt"
  - "{{ ansible_hostname }}.key"
  - "{{ ansible_hostname }}.csr"
  delegate_to: "{{ icinga_ip }}"


