---
- name: Install icinga2
  apt:
    name: {{ item }}
    update_cache: yes
  with_items:
  - icinga2
  - icinga2-ido-mysql
  notify: Restart icinga client

- name: Tell icinga2 to use ido-mysql
  shell: icinga2 feature enable ido-mysql command

- name: Install some plugin dependencies
  apt:
    cache_valid_time: 21600
    state: latest
    pkg:
    - nagios-plugins-standard
#    - nagios-snmp-plugins
    - python-pysnmp4
#    - python-kerberos

- name: Install some more plugin dependencies
  apt: 
    install_recommends: no
    cache_valid_time: 21600
    state: latest
    pkg:
    - nagios-nrpe-plugin

- name: Install even more plugin dependencies
  apt:
    cache_valid_time: 21600
    state: latest
    pkg:
    - smartmontools
    - libconfig-json-perl

- name: Make check_dhcp setuid
  file: path=/usr/lib/nagios/plugins/check_dhcp mode=4755
