---

#- name: Pull registry container
#  docker_image:
#    name: registry:2

- name: Install pip
  apt:
    name: python-pip
    state: present
    update_cache: yes

- name:
  pip:
    name: docker-py

- name: Run the registry
  docker:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
    - "5000:5000"

- name: Pull wikimedia container
  docker_image:
    name: wikimedia/mediawiki:{{ mediawiki_version }}

- name: Tag and push wikimedia container to private registy
  docker_image:
    name: wikimedia/mediawiki:{{ mediawiki_version }}
    repository: localhost:5000/mediawiki
    tag: {{ mediawiki_version }}
    push: yes

- name: Remove local containers
  docker_image:
    name: "{{ item }}"
    state: absent
  with_items:
  - wikimedia/mediawiki:{{ mediawiki_version }}
